### ISSUE TITLE
Not Seeing Shipping Information

### ISSUE THREAD

**Issue by slavakurilyak** [chec/commercejs-nextjs-demo-store#100]
Hey 👋. 

When replicating the demo, I am having an issue seeing shipping information on the order page within Commerce.js

Here's a screenshot of what I see.

![screen](https://user-images.githubusercontent.com/6625584/92170106-eb5e1680-edef-11ea-84d4-3984ac16a1f8.jpg)

Please advise.

**Comment by robbieaverill** [comment]
Hi there, the shipping information is displayed in a separate section: "Shipping address"

**Comment by robbieaverill** [comment]
For example: 
![image](https://user-images.githubusercontent.com/5170590/92176414-42b1b600-edf3-11ea-9092-45374020fceb.png)

**Comment by slavakurilyak** [comment]
@robbieaverill I am not seeing the `Shipping Address` section.

Here is what I see:

![screen 1](https://user-images.githubusercontent.com/6625584/92178226-f23c5780-edf6-11ea-9a27-dffc5fdddad2.jpg)

![screen](https://user-images.githubusercontent.com/6625584/92178140-bf925f00-edf6-11ea-87f1-8f21a670098f.jpg)

**Comment by robbieaverill** [comment]
I see. The product "NotSoBasic Socks" in this case does not have physical delivery enabled, so the shipping address is not captured against the order. Is the product one of the defaults that is created by the demo store's seeder?

**Comment by slavakurilyak** [comment]
@robbieaverill The socks are a new product, not part by the seeder. The physical delivery is enabled for this product.

Here's what I see from Commerce.js side:

![screen](https://user-images.githubusercontent.com/6625584/92182635-02593480-ee01-11ea-8edd-f88376d647f6.jpg)

Here's what I see from Next.js side:

![Screen Recording 2020-09-03 at 04 15 57 PM](https://user-images.githubusercontent.com/6625584/92182647-0a18d900-ee01-11ea-94d8-8a02d5755ef9.gif)

**Comment by robbieaverill** [comment]
You need to click "Enable" in the "Shipping Options" section of that first screenshot to enable shipping for the product

**Comment by slavakurilyak** [comment]
@robbieaverill Thanks for clarifying. 

I added the US and Canada to the Commerce.js settings via [https://dashboard.chec.io/settings/shipping](https://dashboard.chec.io/settings/shipping).

![screen 1](https://user-images.githubusercontent.com/6625584/92184963-65e66080-ee07-11ea-853a-6dc9476c4c28.jpg)

![screen 2](https://user-images.githubusercontent.com/6625584/92184968-6848ba80-ee07-11ea-95d1-a3fee0de1532.jpg)

After redeploying the site, I see the following error:

![screen](https://user-images.githubusercontent.com/6625584/92184888-2f104a80-ee07-11ea-8ecb-72e23e757841.jpg)

**Comment by robbieaverill** [comment]
@slavakurilyak have you enabled the "US and Canada" shipping zone in your product configuration? It's in the "Shipping Options" section from your earlier screenshot.

**Comment by slavakurilyak** [comment]
@robbieaverill That worked! I needed to click to enable "Shipping Options" and enable zone for "US and Canada". Consider adding a note for shipping options in the README file. 🙌
