### ISSUE TITLE
Add Size to Checkout Page

### ISSUE THREAD

**Issue by slavakurilyak** [chec/commercejs-nextjs-demo-store#101]
Please add size (variations) to the checkout page

<img width="553" alt="Image 2020-09-16 at 10 03 14 AM" src="https://user-images.githubusercontent.com/6625584/93369272-007d7100-f804-11ea-98eb-045232671f65.png">

**Comment by robbieaverill** [comment]
Hi @slavakurilyak, it's a good idea to list all selected variants here, thanks for the suggestion.

If you feel like making a pull request, I'd happily review one - otherwise we'll get to this when we have a chance to.

**Comment by robbieaverill** [comment]
@slavakurilyak has implemented this in #102 - thank you for your contribution!
