### ISSUE TITLE
Product image previews not loading at the checkout

### ISSUE THREAD

**Issue by eufandem** [chec/commercejs-nextjs-demo-store#103]
<img width="703" alt="Screen Shot 2020-10-01 at 11 31 06 AM" src="https://user-images.githubusercontent.com/29156467/94849140-d027fc00-03d9-11eb-946a-43704fdfcecf.png">

**Comment by robbieaverill** [comment]
Related: https://github.com/chec/commercejs-nextjs-vercel/issues/5

We can probably take the solution from that repo and apply it here as well.

**Comment by robbieaverill** [comment]
The other repo's patch is here: https://github.com/chec/commercejs-nextjs-vercel/pull/6

**Comment by botex98** [comment]
@robbieaverill may I solve this issue?

**Comment by robbieaverill** [comment]
@botex98 yes please!

**Comment by robbieaverill** [comment]
Fixed in #106, thanks @botex98
