### ISSUE TITLE
Change `commerce.services.localeListCountries` to `commerce.services.localeListShippingCountries`

### ISSUE THREAD

**Issue by jaepass** [chec/commercejs-nextjs-demo-store#116]
Change `commerce.services.localeListCountries` to `commerce.services.localeListShippingCountries` for better handling of populating available shipping countries
For more context https://github.com/chec/commercejs-nextjs-demo-store/issues/114#issuecomment-709488701

**Comment by dalmia007** [comment]
@jaepass is that the only change required? Just changing one thing?

**Comment by drobiu** [comment]
How do I check if my solution works? How to execute the checkout page/render it? Also on what branch should I work on?

**Comment by robbieaverill** [comment]
Hi @drobiu, see https://github.com/chec/commercejs-nextjs-demo-store#overview

**Comment by drobiu** [comment]
What is the intended functionality after the change?

**Comment by drobiu** [comment]
Also is there a way to get existing checkout token inside the js file?

**Comment by jaepass** [comment]
state is being handle with redux store and all data objects are being passed in as props, so the way you've passed the checkout object in works
