### ISSUE TITLE
Adding Table of Content to Readme.md 

### ISSUE THREAD

**Issue by ng29** [chec/commercejs-nextjs-demo-store#120]
Hey @robbieaverill / @john-raymon / @jaepass 

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

It will help users to have a better experience and will avoid unnecessary scrolling on the page.

I would like to work on this issue.

Cheers,

**Comment by robbieaverill** [comment]
We'll gladly review a pull request if you'd like to make one, but we don't need an issue to track it. Thanks!

**Comment by ng29** [comment]
> We'll gladly review a pull request if you'd like to make one, but we don't need an issue to track it. Thanks!

Sure @robbieaverill please review and merge my changes for toc 
https://github.com/chec/commercejs-nextjs-demo-store/pull/121

Cheers
