### ISSUE TITLE
Menu Popup on devices with resolution less than 720px ,bg color looks little aweful, need to optimise that

### ISSUE THREAD

**Issue by akashrajput25** [chec/commercejs-nextjs-demo-store#130]

**Comment by robbieaverill** [comment]
I assume we're talking about this:
![image](https://user-images.githubusercontent.com/5170590/99856815-ac15ab00-2b3e-11eb-927a-6a176b00c1ba.png)

cc @blazepollard

**Comment by akashrajput25** [comment]
yeaa , you got it right, theme is too basic, according to the website's theme, also bottom is not fully covered by the menu.color combination is also not matching, keeping website's theme in view.

**Comment by blazepollard** [comment]
Let's go with a dark background (inherit from text color) and white links on the navigation drop down. 

@robbieaverill

**Comment by ltfschoen** [comment]
So the changes to be made to close this issue is to?
* Change background colour to black
* Change link text colour to white
* Stretch the mobile menu popup so its height extends to the bottom of any screen

**Comment by akashrajput25** [comment]
Yaa that will work

**Comment by ltfschoen** [comment]
Ok I created a PR, so it looks like:

![Screen Shot 2020-12-13 at 4 13 25 am](https://user-images.githubusercontent.com/6226175/101991127-c2a6c080-3cfe-11eb-8993-22d8e56cb940.png)

And on shorter screen sizes ~320 height, it doesn't crop the top "Home" menu item, as shown below:

![Screen Shot 2020-12-13 at 4 29 21 am](https://user-images.githubusercontent.com/6226175/101991143-e10cbc00-3cfe-11eb-85fc-73a375adca06.png)

**Comment by akashrajput25** [comment]
Yaa better
