### ISSUE TITLE
Upgrade to Next.js 10

### ISSUE THREAD

**Issue by robbieaverill** [chec/commercejs-nextjs-demo-store#139]
Next.js v10 was just released (🎉 ) which includes a number of exciting new features, including [automatic image optimisation](https://nextjs.org/blog/next-10#built-in-image-component-and-automatic-image-optimization) and potentially [analytics](https://nextjs.org/blog/next-10#nextjs-analytics).
Let's upgrade to Next.js 10!

Blog: https://nextjs.org/blog/next-10

**Comment by slavakurilyak** [comment]
Upgrading to Next.js v10.0.0+ will improve the [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fcommercejs-demo-store.netlify.app%2F&tab=mobile) score for this demo!

Here is the current mobile score:

<img width="642" alt="screen 1" src="https://user-images.githubusercontent.com/6625584/104085498-cf86d900-5204-11eb-9379-08204afa217f.png">

Here is the current desktop score:

<img width="647" alt="screen 3" src="https://user-images.githubusercontent.com/6625584/104085496-cdbd1580-5204-11eb-9506-97fb35125a18.png">
