### ISSUE TITLE
Shipping validation error

### ISSUE THREAD

**Issue by eufandem** [chec/commercejs-nextjs-demo-store#151]
<img width="1243" alt="Screen Shot 2020-11-18 at 5 08 26 PM" src="https://user-images.githubusercontent.com/29156467/99607449-b1e58200-29c0-11eb-9f44-b501dcc2c1c5.png">

Error should be more contextual
There shouldn't be an error in the first place

**Comment by eufandem** [comment]
@robbieaverill im still getting this error

**Comment by robbieaverill** [comment]
The PR hasn't been merged yet, see #152
