### ISSUE TITLE
After successful login, UI renders "... logged out"

### ISSUE THREAD

**Issue by jaepass** [chec/commercejs-nextjs-demo-store#156]
This message shows after a successful login. Only after a hard refresh the account page with order details renders correctly

<img width="1677" alt="Screen Shot 2020-11-24 at 1 27 57 PM" src="https://user-images.githubusercontent.com/48780927/100154887-2e61e000-2e5b-11eb-90da-9d87a8baebaa.png">

**Comment by robbieaverill** [comment]
Fixed in #154
