### ISSUE TITLE
Add category in dashboard messes up a Link in CategoryBanner.js

### ISSUE THREAD

**Issue by LB22** [chec/commercejs-nextjs-demo-store#157]
If I add a new category and refresh I get the error "Error: Failed prop type: The prop `href` expects a `string` or `object` in `<Link>`, but got `undefined` instead."

I traced it by luck to `<Link href={item.link}>` in components/homepage/CategoryBanner.js.

The error goes away if I remove the new category I created in the dashboard, or if I change the Link to `<Link href="/">`

**Comment by robbieaverill** [comment]
cc @jaepass

**Comment by jaepass** [comment]
Thanks for raising this @LB22, I'll look into this. 

@robbieaverill I think we'll need to completely remove this category block.

**Comment by robbieaverill** [comment]
Sounds good. If not, we need to ensure that any attributes of the extra category data we consume in this demo store are either attributes that the Chec API provides, or have null safety handling for cases like this where we've added extra properties that don't exist in the Chec API.

**Comment by jaepass** [comment]
Fixed with https://github.com/chec/commercejs-nextjs-demo-store/pull/204
