### ISSUE TITLE
Products not rendering because chec.io does not recognise the seeded association between each product and category anymore

### ISSUE THREAD

**Issue by ltfschoen** [chec/commercejs-nextjs-demo-store#168]
When I clone the latest commit https://github.com/chec/commercejs-nextjs-demo-store/commit/c9796add2b4a3cefca2c49cb3dfb9257a51e02a8, and then delete all products and categories from chec.io, and then configure my .env file using my chec.io sandbox public key and run:
```
yarn
yarn seed
yarn build
yarn dev
```
when i go to this page, none of the products are shown
![Screen Shot 2020-12-12 at 10 52 20 am](https://user-images.githubusercontent.com/6226175/101965565-36968980-3c69-11eb-80fa-5b8eb4f4f840.png)

It appears to be because the way we associate each product with a category by writing `"category_id": "categories[0].id"` in products.json isn't working anymore for some reason.
I tried to get this to work with the latest 'master' branch, and also with
This functionality worked when I originally forked the repo back in August 13 2020, but I tried using that same old commit again now, but it no longer works https://github.com/ltfschoen/commercejs-nextjs-demo-store/commit/192a219808c56e19775f8e04ba666c57bd01bd5e, so i suspect that the chec.io site isn't processing the association.

If we write `"link": "products[0].id",` in assets.json, it still works though. 

This is annoying, because previously we could define the association in the seed files (i.e. which product belongs to which category), as follows:

```
  {
    "product": {
      "name": "Face & Body Roller",
      "description": "Enrich your morning and evening beauty ritual and to help reduce the appearance of puffiness and wrinkles",
      "price": "18.00",
      "category_id": "categories[2].id"
    },
...
```

But now that this doesn't work, we have to run the seed to upload the categories first so chec.io generates their id's, then we have to use a `categories` property instead of `category_id`, and manually replace each of its `id` fields (i.e. `cat_BkyN5YVbxl0b69`) with the latest category id from chec.io, and then run `yarn seed` again for the products to be uploaded along with that association. The other alternative is to set the category of each product in the chec.io https://dashboard.chec.io/products, but that is extremely time consuming as you can't just run a find/replace command.

```
[
  {
    "product": {
      "name": "Eyebrow Wax",
      "description": "",
      "price": "15.00"
    },
    "categories": [
      {
        "id": "cat_BkyN5YVbxl0b69",
        "slug": "treatments-facial",
        "name": "Facial Treatments"
      }
    ]
  },
```

**Comment by C3PablO** [comment]
any update of this? for me the only options that works is adding the category to each product in the chec.io admin

**Comment by robbieaverill** [comment]
@C3PablO we haven't had a chance to look into this yet. Your suggested workaround is great, and I'd recommend anyone else with this problem do the same thing. Our seeder script is not currently able to seed everything that is required for demo stores to function, so still some operations must be done in the dashboard. This issue is one that we would like to fix at some stage though. We also welcome contributions to this repo or the [seeder](https://github.com/chec/seeder) to fix it in the meantime.

**Comment by ltfschoen** [comment]
unfortunately when you're forecast that in future you'd have a large number of products, the thought of having to do "manual" workarounds like adding the categories to thousands of products using an admin dashboard rather than just running a script is a showstopper. the seeding feature would be necessary if you want to backup and then restore your data in production too, not just for the demo store, so i'm actually surprised that commercejs doesn't just sponsor this fix and some of the other showstopper issues since they'd profit from more paying customers. if this was fixed back in December they likely have at least one more customer that would have been paid them US$237 in fees over the last 3 months.

**Comment by robbieaverill** [comment]
Hey there, we have an API that you can use to script this kind of thing. Third issue is specifically for our seeder, and for people who want to quickly install our sample data to use our demo store.

**Comment by ltfschoen** [comment]
Oh right, I wasn't aware of that. I'd all but given up on it back in December.

**Comment by robbieaverill** [comment]
Sorry for the confusion. What you're trying to achieve here is definitely achievable using our create/update product/category (docs here: https://commercejs.com/docs/api/). For this issue, either the seed files in this demo store repository, or the seeder itself perhaps, need to be updated to handle multiple category associations.

Commerce.js has dedicated support available for paid plans.
