### ISSUE TITLE
Category meta not defined error even though the meta property is optional

### ISSUE THREAD

**Issue by ltfschoen** [chec/commercejs-nextjs-demo-store#175]
I think this line should be changed https://github.com/chec/commercejs-nextjs-demo-store/blob/master/components/homepage/CategoryBanner.js#L27 to be `{ item.meta && item.meta.image && (`, otherwise if the optional property `meta` is not defined in the categories.json, then the homepage doesn't load. It is an optional field in the docs https://commercejs.com/docs/api/#update-category

**Comment by robbieaverill** [comment]
Yep, good catch. You can also do `image.meta?.image` since we have an ECMAScript transpilation.
