### ISSUE TITLE
Categories are displayed in UI in the reverse order from the order they are listed in categories.json

### ISSUE THREAD

**Issue by ltfschoen** [chec/commercejs-nextjs-demo-store#176]
I think this recent commit to the 'master' branch has caused the categories that get listed on this page http://localhost:3000/collection to now be listed in the reverse order from the order that they are listed in the categories.json file.

**Comment by robbieaverill** [comment]
Thanks for raising this. I don't see this as a problem for this repository, although I will accept a pull request to adjust the sort order so it is in ascending order by ID if it isn't already so.

If you want to control the order the categories are loaded in for your own store, you may provide `{ sortBy: 'id', sortDirection: 'desc' }` (for example) as the `params` argument to the "list categories" call here: https://github.com/chec/commercejs-nextjs-demo-store/blob/master/pages/_app.js#L34.
