### ISSUE TITLE
"Add to cart" currency symbol

### ISSUE THREAD

**Issue by zb2oby** [chec/commercejs-nextjs-demo-store#180]
Hi,

The" add to cart" button is rendered with an hard-codded currency symbol : 

```${this.getPrice()}```

it should be : 

```{`this.getCurrencySymbol(product.price.formatted_with_symbol)}{this.getPrice()}```

maybe add it in utils : 

`getCurrencySymbol(priceFormattedWithSymbol) {
    return priceFormattedWithSymbol.substring(1, 0);
  }`

**Comment by robbieaverill** [comment]
Thank you @zb2oby
