### ISSUE TITLE
Update node-sass to support newest versions of Node

### ISSUE THREAD

**Issue by IvanSmiths** [chec/commercejs-nextjs-demo-store#190]
Hello there! I'm getting this error while using the script "yarn start" to start a local development.

error - ./style/scss/style.scss
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)

I'm using Node version v14.15.5.

**Comment by robbieaverill** [comment]
Hi there, it sounds like the build tools don't support node 14 yet. Could you try using node 12?

**Comment by IvanSmiths** [comment]
Hi and thanks for the quick response. I'll try it for sure, for now i'm going to see if i can find a workaround with version 14.

**Comment by robbieaverill** [comment]
Sounds good, I'll relabel this issue to update the build tools to support newer versions of node.

**Comment by PaitoAnderson** [comment]
@IvanSmiths This should be fixed now since this project was updating to Next 10, I was able to run `yarn start` with Windows 64-bit and Node version v14.17.1 without issue.

**Comment by robbieaverill** [comment]
Thanks team, reopen if necessary
