### ISSUE TITLE
Can someone help me show the products? 

### ISSUE THREAD

**Issue by talmax1124** [chec/commercejs-nextjs-demo-store#194]
I have tried contacting people on slack and they have been unsuccessful at helping me resolve my problem. Can any of you help me make the products show with my API public key. I can't see any of the products. I did not change any of the products or categories that came with the repo. 

What I mean is there is nothing appearing in the /collections page

You can reply to this repo or if you can, email me at carlitosdiazplaza@gmail.com

Thanks!

**Comment by robbieaverill** [comment]
Hi @talmax1124, please ensure you follow the readme guide here: https://github.com/chec/commercejs-nextjs-demo-store#manual-setup-and-netlify-deployment. The main thing is to make sure you swap the demo store's API key in the `.env` file with your own API key. You can either seed the products (see step 3 in the referenced readme above) or create some of them manually.

If you don't see the products in your store, there could be a number of things causing this problem. Most notably:

* Your API key is missing, incorrect, or incorrectly connected into your application. Check your environment file, and add some breakpoints/debugging to ensure it is loaded correctly into the server-side phase of your application where `commerce.products.list()` is called.
* You haven't switched from the demo store's API key to your own
* You haven't set up any products yet

Please feel free to reach out on Slack. We'll reserve the issue tracker on this repository for bug reports.
