### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by mattmi91** [chec/commercejs-nextjs-demo-store#225]
I get this error everytime I go from page to page, how to solve?
.next\static\chunks\pages\collection.js (50:20) @ Collections.renderSidebar

  48 | return (
  49 |   <>
> 50 |     {categories.map(category => (
     |                ^
  51 |       <div key={category.id} className="custom-container">
  52 |         <div className="row">
  53 |           <div className="col-2 d-none d-lg-block position-relative">

**Comment by robbieaverill** [comment]
Hi @mattmi91, did you find a solution for this?

**Comment by mattmi91** [comment]
yes I ended up changing line 50 to this
{categories && categories.map(category => (
the categories && was the solution but I now have another problem my products do not show up on that collection page but they do on the home page so my my api key is working but not for the collection page?

**Comment by robbieaverill** [comment]
Feel free to join our community Slack channel for integration support: http://slack.commercejs.com.

Regarding the categories patch, if you want to make a pull request to update this repository with that change we'd welcome that 🙂

**Comment by mattmi91** [comment]
> Feel free to join our community Slack channel for integration support: http://slack.commercejs.com.
> 
> Regarding the categories patch, if you want to make a pull request to update this repository with that change we'd welcome that 🙂

**Comment by mattmi91** [comment]
> Feel free to join our community Slack channel for integration support: http://slack.commercejs.com.
> 
> Regarding the categories patch, if you want to make a pull request to update this repository with that change we'd welcome that 🙂

im guessing they are not showing because I had to make that change to stop getting the error right when the page loads?
