### ISSUE TITLE
Bug/Store data not persisting going from one getStaticProps product display page to another 

### ISSUE THREAD

**Issue by jaepass** [chec/commercejs-nextjs-demo-store#59]
Store data like items in cart not persisted going from one `getStaticProps` "product detail page" to another after `next-wrapper-redux` udpate

**Comment by robbieaverill** [comment]
I might suggest we refer to "product detail pages" or "product details view" or something rather than PDP - I think "PDP" is a bit of a siloed term we've ended up adopting, but it's not clear what it means to anyone else (including me and Guy!)

**Comment by robbieaverill** [comment]
Regression from #43

**Comment by jaepass** [comment]
so have gone through the docs and issues raised but still stumped on how to merge both server and client states or hydrate correctly.  is `getInitialProps()` still compatible with the latest `next-wrapper-redux` upgrade?
https://github.com/kirill-konshin/next-redux-wrapper/pull/196#
