### ISSUE TITLE
Add a contribution outline doc

### ISSUE THREAD

**Issue by jaepass** [chec/commercejs-nextjs-demo-store#62]

**Comment by botex98** [comment]
Hey. 
Would this bit help?
[Good CONTRIBUTING.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426)

**Comment by jaepass** [comment]
Hi @botex98 thanks for your comment. If you'd like to make a pull request, please edit the doc to be more specific to contribute to the project. The guide you suggested is for a rather wide range of projects and not all points pertain to the repo.

**Comment by kichloo** [comment]
@jaepass Kindly assign this issue to me

**Comment by robbieaverill** [comment]
Thanks for all the interest. It's better that we do this ourselves, to avoid wasting contributors time.
