### ISSUE TITLE
Add option to set up project with Chec CLI demo-store in setup steps

### ISSUE THREAD

**Issue by jaepass** [chec/commercejs-nextjs-demo-store#76]

**Comment by Yashs911** [comment]
Hi, @jaepass I would like to work on this issue. I am new to open source so can you please guide me?

**Comment by robbieaverill** [comment]
Hi @Yashs911, thanks for your interest. You can install this repository as a Commerce.js demo site using our [CLI](https://github.com/chec/cli), where this template is one of the options under the `demo-store` command. This task is to add some instructions for doing this to the readme of this repository.

**Comment by Yashs911** [comment]
@robbieaverill So I need to add this method:

![2](https://user-images.githubusercontent.com/64412143/95415404-c8260a00-094d-11eb-9346-4c6298d7bf6e.JPG)

in the readme file of this repository. Am I correct?

**Comment by robbieaverill** [comment]
Yes that's correct

**Comment by robbieaverill** [comment]
hanks @Yashs911
