### ISSUE TITLE
Netlify onboarding plugin not working

### ISSUE THREAD

**Issue by jaepass** [chec/commercejs-nextjs-demo-store#80]
- Added onboarding plugin to Netlify config, tested and worked fine
- Somehow regressed and now onboarding screen does not show extra template.environment property to input env var

**Comment by jaepass** [comment]
Raised an issue here https://github.com/jlengstorf/netlify-plugin-onboarding/issues/1

**Comment by ScopeyNZ** [comment]
I assume we'll need to update the plugin when it's fixed?

**Comment by jaepass** [comment]
heyhey Guy a patch was added and fixed now. no need for an update on our end. the plugin is now working as expected!

**Comment by ScopeyNZ** [comment]
Sure, but won't the `yarn.lock` be tied to the broken version?

**Comment by ScopeyNZ** [comment]
Nevermind, I was confused to how this works. It didn't require a change to the dependency, something on their servers. All good.

**Comment by jaepass** [comment]
Awesome thanks Guy, yea seemed like a real quick fix, they got on the issue today and patched it in a couple hours.
