### ISSUE TITLE
Totals issue at checkout and receipt page

### ISSUE THREAD

**Issue by eufandem** [chec/commercejs-nextjs-demo-store#93]
<img width="1183" alt="Screen Shot 2020-08-12 at 11 18 29 AM" src="https://user-images.githubusercontent.com/29156467/90053261-12ad4200-dc8f-11ea-8a25-e738ea776f14.png">

**Comment by john-raymon** [comment]
It seems like the wrong total, subtotal is deriving from the checkout token object.

![image](https://user-images.githubusercontent.com/30238579/90056313-a9d4c280-dcac-11ea-9443-0013829ff4ae.png)

**Comment by john-raymon** [comment]
For some reason the `live.line_items.line_total` prices for the items are different from the `live.line_items.price` prices. The live object's total reflects the prices from the `live.line_items.line_total`. 

@robbieaverill @ScopeyNZ  is `live.line_items.price` deprecated? I'm not sure why the two are different prices if in this scenario there's only 1 quantity for each being checked out. 

![image](https://user-images.githubusercontent.com/30238579/90056808-79d9ef00-dcad-11ea-87a5-5dc55b387e73.png)

**Comment by ScopeyNZ** [comment]
Is it adding a variant price? I think the `price` on the line_item response there is the base price for the product, without an variant price deltas added.

**Comment by ScopeyNZ** [comment]
Looking at the products, I'm guessing that first line item (complexion cream) has the "500ml" variant, which will add $57 to the line item total.

**Comment by john-raymon** [comment]
@ScopeyNZ I'm also noticing some discrepancies within the order receipt object. 

Here a variant of the Lip Fantastic product is checked out, but yet the total only shows 34.50 within there but the subtotal is 59.

**Comment by robbieaverill** [comment]
Fixed in #95, nice work @john-raymon
