### ISSUE TITLE
Better error handling when categories are deleted in the backend

### ISSUE THREAD

**Issue by jaepass** [chec/commercejs-nextjs-demo-store#98]
Scenario:
- When a user clones the project, seeds the sample data and sets up the app locally, he/she deletes the sample categories
- The hard coded categories data here https://github.com/chec/commercejs-nextjs-demo-store/blob/master/lib/collections.js does not match up and the UI cannot be rendered

Solutions:
- Better error handling
- Get rid of hardcoded collections data and somehow output dynamically or remove from UI where it is used in home page categories banner and sidebar in shop pages and pdp (added categories feature image and product count)

**Comment by robbieaverill** [comment]
Solutions sound great to me 👍

**Comment by robbieaverill** [comment]
Another scenario for this is when someone clones the project, changes to their own API key, but doesn't seed any data or set up any products/categories.

**Comment by robbieaverill** [comment]
Fixed with #105 for now. Ideally we stop relying on hard coded category/asset information in future, but no need to keep this issue open for that.
